---
- name: Configure Ubuntu and Install Cosmic Installer
  hosts: otnodes
  remote_user: root
  gather_facts: no

  tasks:
  - name: Add firewall rule 22
    ufw:
      rule: allow
      port: '22'
      state: enabled

  - name: Add firewall rule 3000
    ufw:
      rule: allow
      port: '3000'
      state: enabled

  - name: Add firewall rule 5278
    ufw:
      rule: allow
      port: '5278'
      state: enabled

  - name: Add firewall rule 8900
    ufw:
      rule: allow
      port: '8900'
      state: enabled

  - name: Update and upgrade Ubuntu
    apt:
      upgrade: full
      update_cache: yes

  - name: Install initial applications (apt-transport-https, ca-certificates, curl, software-properties-common)
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: Add Docker repository gpg key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu focal stable
      state: present

  - name: Update APT with Docker repository info and install Docker, nodejs, npm, jq, curl, zip, unzip, and git
    apt:
      pkg:
      - docker-ce
      - nodejs
      - npm
      - jq
      - curl
      - zip
      - unzip
      - git
      update_cache: yes
      state: present

  - name: Clone Cosmic Overlay git repository
    git:
      repo: 'https://github.com/CosmiCloud/Cosmic_OverlayV2.git'
      dest: /root/Cosmic_OverlayV2

  - name: Install shelljs
    command:
      chdir: /root/Cosmic_OverlayV2/cron-jobs-node
      cmd: npm i shelljs

  - name: Install express
    command:
      chdir: /root/Cosmic_OverlayV2/cron-jobs-node
      cmd: npm i express

  - name: Install node-cron
    command:
      chdir: /root/Cosmic_OverlayV2/cron-jobs-node
      cmd: npm i node-cron

  - name: Install forever
    command:
      chdir: /root/Cosmic_OverlayV2/cron-jobs-node
      cmd: npm i forever -g
