---
- name: Update Cosmic_Overlay
  hosts: all
  gather_facts: no

  tasks:
    - name: Git pull Cosmic_Overlay files
      git:
      repo: 'https://foosball.example.org/path/to/repo.git'
      dest: /root/Cosmic_OverlayV2
      update: yes
      clone: yes
