---

- name: Uninstall OT-Smoothbrain-Backup
  hosts: all
  gather_facts: no

  tasks:
  - name: Delete /root/OT-Smoothbrain-Backup directory
    file:
      path: /root/OT-Smoothbrain-Backup
      state: absent

  - name: Delete old Restic cron jobs
    cron:
      name: "Ansible: restic backup"
      state: absent

  - name: Delete old Smoothbrain cron jobs
    cron:
      name: "Ansible: Smoothbrain backup"
      state: absent

  - name: Delete old Coldbrain cron jobs
    cron:
      name: "Ansible: Smoothbrain backup"
      state: absent