# This will install the Netdata client on your servers.
#
# Settings to edit:
# CLAIM_TOKEN (Get this from the netdata website "Claim Nodes". Copy the string on the right side.)

---

- name: Install Netdata
  hosts: all
  vars_files: "/root/OT-Ansible-Files-and-Playbooks/hosts-config"
  become: true
  become_method: sudo

  tasks:
  - name: Download the installation script
    get_url:
      url: https://my-netdata.io/kickstart.sh
      dest: ~/kickstart.sh
      mode: +x

  - name: Install Netdata
    command: ~/kickstart.sh --dont-wait --claim-token "{{ claim_token }}" --claim-rooms "{{ claim_rooms }}" --claim-url "{{ claim_url }}"

  - name: Cleanup installation script
    file:
      path: ~/kickstart.sh
      state: absent
