---

# This module will change your server's timezone to your local timezone

- name: Change time on Ubuntu servers to localtime
  hosts: all
  gather_facts: no

  tasks:
    - name: Updating timezone
      timezone:
        name: '{{ timezone }}'

    - name: Rebooting system
      reboot:
