---

# Settings to edit:
# APPLICATION_NAME (Replace with the application name as it appears in Ubuntu)

- name: Install Application
  hosts: all
  gather_facts: no

  tasks:
    - name: Installing Application
      apt:
        name: '{{ install_app_application_name }}'
        state: present
        update_cache: yes
