---

# This will upgrade the Ubuntu servers and reboot if required. This will ONLY upgrade and will not dist-upgrade
# nor will it upgrade from one major version to another. Exp. Ubuntu 18 to Ubuntu 20.

- name: Update Ubuntu OS software. Will reboot if needed!
  hosts: all
  gather_facts: no

  tasks:
    - name: Upgrading Ubuntu OS
      apt:
        upgrade: full
        update_cache: yes

    - name: check if a reboot is required
      shell: "[ -f /var/run/reboot-required ]"
      failed_when: False
      register: reboot_required
      changed_when: reboot_required.rc == 0
      notify: reboot

  handlers:
    - name: reboot
      command: /sbin/reboot
