# This will claim/re-claim the Netdata client on your servers.

# Settings to edit:
# CLAIM_TOKEN (Get this from the netdata website "Claim Nodes". Copy the string on the right side.)
---

- name: Claim/reclaim a Netdata client
  hosts: all
  vars:
    claim_token: CLAIM_TOKEN
  gather_facts: no

  tasks:
  - name: Unclaim node if already claimed
    file:
      path: /var/lib/netdata/cloud.d
      state: absent

  - name: Install uuid-runtime
    apt:
      name: uuid-runtime
      state: present

  - name: Claiming node
    shell: sudo netdata-claim.sh "{{ claim_token }}" -id=$(uuidgen)

  - name: Restart netdata service
    service:
      name: netdata
      state: restarted
