# This will install the Netdata client on your servers.
# Edit "shell: sudo netdata-claim.sh" line to add your claim token.
#
# Settings to edit:
# CLAIM_TOKEN (Get this from the netdata website "Claim Nodes". Copy the string on the right side.)

---

- name: Install Netdata
  hosts: all
  vars:
    claim_token: CLAIM_TOKEN
  gather_facts: no

  tasks:
    - name: Copy kickstart.sh file to server
      copy:
        src: ~/OT-Ansible-Files-and-Playbooks/data/kickstart.sh
        dest: /root/
        owner: root
        group: root
        mode: '0700'

    - name: Install Netdata
      shell: yes "" | /root/OT-Ansible-Files-and-Playbooks/data/kickstart.sh

    - name: Claiming node
      shell: sudo netdata-claim.sh "{{ claim_token }}"
