---

# This module will limit journalctl to 150M. It will auto delete beyond this size.

# Settings to edit:
# USERNAME_TO_ADD

- name: Limit journalctl log size to user-set value
  hosts: all
  vars:
    size_limit: 150M
  gather_facts: no

  tasks:
    - name: Set limit of journalctl log
      replace:
        path: /etc/systemd/journald.conf
        regexp: '#SystemMaxUse='
        replace: SystemMaxUse={{ size_limit }}
    
    - name: Restart journalctl service
      service:
        name: systemd-journald
        state: restarted