---

# This module will create a new passwordless sshkey on each server and send that public key to the backup server
# SETTING TO CHANGE IN CONFIG:
# smoothbrain_server_ip: 'SMOOTHBRAIN_SERVER_IP' Put the IP/domain of your smoothbrain server here.
# smoothbrain_server_user: 'USERNAME'
# smoothbrain_server_user_pass: 'USERNAME_PASS'
# smoothbrain_server_port: '22' # Only change if you know you changed the SSH port

- name: Create SSH keys and send to Smoothbrain server
  hosts: all
  gather_facts: yes

  tasks:
    - name: Create /root/.ssh directory
      file:
        path: /root/.ssh
        state: directory
        mode: '700'
    
    - name: Installing sshpass
      apt:
        name: sshpass
        state: present
        update_cache: yes
  
    - name: Remove existing private key
      file:
        path: /root/.ssh/id_ecdsa
        state: absent

    - name: Remove existing public key
      file:
        path: /root/.ssh/id_ecdsa.pub
        state: absent

    - name: Create new SSH keys
      openssh_keypair:
        path: ~/.ssh/id_ecdsa
        type: ecdsa
        size: 521
        state: present
        comment: '{{ node_name }}'
      register: ssh_key_values

    - name: Send the public key to the Smoothbrain server
      command: sshpass -p {{ smoothbrain_server_user_pass }} ssh-copy-id -p {{smoothbrain_server_port}} -i /root/.ssh/id_ecdsa.pub -o StrictHostKeyChecking=no {{smoothbrain_server_user}}@{{smoothbrain_server_ip}}
        
