---

# This auto-restarts the server every day at midnight.

- name: Setup daily server restart
  hosts: otnodes
  gather_facts: no

  tasks:
    - name: Adding reboot schedule to crontab
      cron:
        name: Reboot schedule
        minute: '{{ restart_minute }}'
        hour: '{{ restart_hour }}'
        day: '{{ restart_day }}'
        month: '{{ restart_month }}'
        weekday: '{{ restart_weekday }}'
        job: "reboot"
