---

# This is a collection of monitors to check various states at regular scheduled intervals.
# Monitors performed:
#  Check for bids last 15 minutes

# Settings to edit:
# All "bidcheck_" entries

- name: Install Monitors
  hosts: all
  vars:
    bidcheck_minute: */15 # Checks every 15 minutes
    bidcheck_hour: *
    bidcheck_day: *
    bidcheck_month: *
    bidcheck_weekday: *

  gather_facts: no

  tasks:
    - name: Create directories
      file:
        path: /root/OT-Ansible-Files-and-Playbooks/manage/data
        state: directory
        mode: '0755'

    - name: Create directories
      file:
        path: /root/OT-Ansible-Files-and-Playbooks/manage/ubuntu/data
        state: directory
        mode: '0755'

    - name: Install send.sh
      copy:
        src: ~/OT-Ansible-Files-and-Playbooks/manage/data/send.sh
        dest: /root/OT-Ansible-Files-and-Playbooks/manage/data/send.sh
        owner: root
        group: root
        mode: '0700'

    - name: Install config.sh
      copy:
        src: ~/OT-Ansible-Files-and-Playbooks/manage/data/config.sh
        dest: /root/OT-Ansible-Files-and-Playbooks/manage/data/config.sh
        owner: root
        group: root
        mode: '0600'

    - name: Install bid check monitor
      copy:
        src: ~/OT-Ansible-Files-and-Playbooks/manage/ubuntu/data/bid_check.sh
        dest: /root/OT-Ansible-Files-and-Playbooks/manage/ubuntu/data/bid_check.sh
        owner: root
        group: root
        mode: '0700'

    - name: Delete existing monitor (bid check) schedule from cron
      cron:
        name: Monitor Bid Check
        state: absent

    - name: Add monitor (bid check) schedule to cron (every 15 minutes)
      cron:
        name: Monitor Bid Check
        minute: "{{ bidcheck_minute }}"
        hour: "{{ bidcheck_hour }}"
        day: "{{ bidcheck_day }}"
        month: "{{ bidcheck_month }}"
        weekday: "{{ bidcheck_weekday }}"
        job: "/root/OT-Ansible-Files-and-Playbooks/manage/ubuntu/data/bid_check.sh"
