---

# Settings to edit:
# APPLICATION_NAME (Replace with the application name as it apepars in Ubuntu)

- name: Remove Application from Ubuntu server
  hosts: otnodes
  vars_files: "/root/OT-Ansible-Files-and-Playbooks/hosts-config"
  gather_facts: no

  tasks:
    - name: Removing Application
      apt:
        name: "{{ remove_app_application_name }}"
        state: absent
