# This will install the Netdata client on your servers.
# Edit "shell: sudo netdata-claim.sh" line to add your claim token.

---

- name: Install Netdata
  hosts: all
  gather_facts: no

  tasks:
  - name: Unclaim node
    file:
      path: /var/lib/netdata/cloud.d
      state: absent

  - name: Install uuid-runtime
    apt:
      name: uuid-runtime
      state: present

  - name: Claiming node
    shell: sudo netdata-claim.sh EDIT_PUT_YOUR_CLAIM_TOKEN -id=$(uuidgen)

  - name: Restart netdata service
    service:
      name: netdata
      state: restarted
