# This will install the Netdata client on your servers.
# Edit "shell: sudo netdata-claim.sh" line to add your claim token.

---

- name: Install Netdata
  hosts: all
  gather_facts: no

  tasks:
    - name: Copy kickstart.sh file to server
      copy:
        src: ~/OT-Ansible-Files-and-Playbooks/data/kickstart.sh
        dest: /root/
        owner: root
        group: root
        mode: '0700'

    - name: Install Netdata
      shell: yes "" | ./kickstart.sh

    - name: Claiming node
      shell: sudo netdata-claim.sh EDIT_PUT_YOUR_CLAIM_TOKEN
