# This will install the Netdata client on your servers.
# Edit "shell: sudo netdata-claim.sh" line to add your claim token.

---

- name: Install Netdata
  hosts: all
  gather_facts: no

  tasks:
    - name: Claiming node
      shell: sudo netdata-claim.sh EDIT_PUT_YOUR_CLAIM_TOKEN
