---

# This module will create anew user account, add them to the SUDO group, add your public SSH key to their ~/.ssh/authrized_keys file, and disable the root account.
# To encrypt the password run the following:
# python3 -c 'import crypt,getpass;pw=getpass.getpass();print(crypt.crypt(pw) if (pw==getpass.getpass("Confirm: ")) else exit())'
# Copy the output to the 'password' area of this config.
#
# Settings to edit:
# USERNAME_TO_ADD (two places)
# ENCRYPTED_PASS (one place)
# ssh-rsa_COPY_PUBLIC_KEY_HERE (one place)
#

- name: Add new sudo user account to Ubuntu and disable root account
  hosts: all
  gather_facts: no

  tasks:
    - name: Create new user account
      user:
        name: USERNAME_TO_ADD #Edit this AFTER the ": "
        groups: sudo
        append: yes
        state: present
        create_home: yes
        shell: /bin/bash
        password: ENCRYPTED_PASS #Edit this AFTER the ": "

    - name: Add public key to users's .ssh/authorized_keys file
      authorized_key:
        user: USERNAME_TO_ADD #Edit this AFTER the ": "
        state: present
        manage_dir: yes
        key: ssh-rsa_COPY_PUBLIC_KEY_HERE  #Edit this AFTER the ": "

    - name: Disable root from being allowed to login
      replace:
        path: /etc/ssh/sshd_config
        regexp: 'PermitRootLogin yes'
        replace: 'PermitRootLogin no'

    - name: Disable root account
      user:
        name: root
        password: !

    - name: Changing PermitRootLogin to "no"
      replace:
        path: /etc/ssh/sshd_config
        regexp: '#PasswordAuthentication yes'
        replace: 'PasswordAuthentication no'

    - name: Restart SSH daemon
      service:
        name: sshd
        state: restarted
