---
- name: Update Cosmic_Overlay
  hosts: all
  gather_facts: no

  tasks:
    - name: Git pull Cosmic_Overlay files
      git:
      repo: 'https://github.com/CosmiCloud/Cosmic_OverlayV2.git'
      dest: /root/Cosmic_OverlayV2
      update: yes
      clone: yes
