- name: Update servers node and Cosmic_Overlay settings files with local settings files
  hosts: all
  gather_facts: yes

  tasks:
  - name: Remove existing node config
    file:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      state: absent

  - name: Remove existing overlay config
    file:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      state: absent

  - name: Copy node config file to server
    copy:
      src: ~/OT-Ansible-Files-and-Playbooks/data/node_config.json
      dest: /root/Cosmic_OverlayV2/configurations
      owner: root
      group: root
      mode: '0600'

  - name: Copy overlay config file from example
    command: 'cp example-overlay_config.json overlay_config.json'
    args:
      chdir: /root/Cosmic_OverlayV2/configurations/

  - name: Edit node config with IP address
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: your external IP or domain name here
      replace: "{{ ansible_facts['default_ipv4']['address'] }}"

  - name: Edit node config with initial deposit amount
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: 'your initial deposit amount in TRAC with 18 decimals, 1 TRAC = 1000000000000000000 '
      replace: "{{ initial_deposit_amount }}"

  - name: Edit node config with operational wallet public key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: your ethereum wallet address here
      replace: "{{ op_pub_key }}"

  - name: Edit node config with operational wallet private key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: your ethereum wallet's private key here
      replace: "{{ op_priv_key }}"

  - name: Edit node config with management wallet public key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: your ethereum management wallet public key here
      replace: "{{ mgmt_pub_key }}"

  - name: Edit node config with dh_price_factor
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: DH_PRICE_FACTOR
      replace: "{{ dh_price_factor }}"

  - name: Edit node config with dh_max_holding_time_in_minutes
    replace:
      path: /root/Cosmic_OverlayV2/configurations/node_config.json
      regexp: DH_HOLDING_TIME_MINUTES
      replace: "{{ dh_max_holding_time_in_minutes }}"

# Write cosmic overlay settings

  - name: Edit cosmic overlay config with the mainnet environment
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: testnet
      replace: mainnet

  - name: Edit cosmic overlay config with the node name
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*node name here\*
      replace: "{{ node_name }}"

  - name: Edit cosmic overlay config with the telegram bot token
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*telegram bot token here\*
      replace: "{{ telegram_bot_token }}"

  - name: Edit cosmic overlay config with the telegram chat_id
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*telegram chat id here\*
      replace: "{{ telegram_chat_id }}"

  - name: Edit cosmic overlay config with the AWS region
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*aws region here\*
      replace: "{{ aws_region }}"

  - name: Edit cosmic overlay config with the AWS access key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*aws key id here\*
      replace: "{{ aws_access_key_id }}"

  - name: Edit cosmic overlay config with the AWS secret access key
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*aws secret access key here\*
      replace: "{{ aws_secret_access_key }}"

  - name: Edit cosmic overlay config with the AWS bucket name
    replace:
      path: /root/Cosmic_OverlayV2/configurations/overlay_config.json
      regexp: \*aws bucket here\*
      replace: "{{ aws_bucket_name }}"
